name: lint-and-build
on: push
env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPOSITORY: gcloud-kubectl-helm
  # set this in Github repository -> setting -> Secrets and Variables
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # should be set automatic by Github actions
  #GITHUB_REPOSITORY_OWNER:
jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine
    steps:
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: lint-scripts
      run: ".github/scripts/lint-scripts.sh"
  build-image:
    runs-on: ubuntu-latest
    needs:
    - lint-scripts
    steps:
    - uses: actions/checkout@v3.3.0
    - name: build
      run: ".github/scripts/build-image.sh"
